# [[redirects]]
#  from = "/*"
#  to = "https://meridian-verify.vercel.app/:splat"
#  status = 200
#  force = true # COMMENT: ensure that we always redirect
#  headers = {X-From = "Netlify"}
#  signed = "API_SIGNATURE_TOKEN"